### PR TITLE
[CSUB-1062] Remove EVM wallet utils & evm-send command

### PR DESCRIPTION
**Pull request by pLabarta**
# Description of proposed changes

<describe what this PR is about and why we want it>

---

Practical tips for PR review & merge:

- [ ] All GitHub Actions report PASS
- [ ] Newly added code/functions have unit tests
  - [ ] Coverage tools report all newly added lines as covered
  - [ ] The positive scenario is exercised
  - [ ] Negative scenarios are exercised, e.g. assert on all possible errors
  - [ ] Assert on events triggered if applicable
  - [ ] Assert on changes made to storage if applicable
- [ ] Modified behavior/functions - try to make sure above test items are covered
- [ ] Integration tests are added if applicable/needed

### CODE REVIEW

**Review by atodorov — APPROVED** [review]
Blocked by the work on CSUB-1054. The rest LGTM.

**Comment by atodorov** [comment]
FYI rebased onto latest `dev`

**Review by atodorov — CHANGES_REQUESTED** [review]
Failing integration test for removed `evm send`! All related scenarios for this command need to be removed as well. 

Also requires a rebase - Ideally after #232 gets merged!

**Comment by atodorov** [comment]
> FYI rebased onto latest `dev`

Rebased again and resolved a conflict with import statements.

**Review by atodorov — APPROVED** [review]

**Review by beqaabu — APPROVED** [review]
Changes lgtm just wanted to know out of curiosity why is the send command being removed from the cli

**Pull request merged**
