### PR TITLE
CSUB-860: Automatically upgrade WASM runtime on Devnet

### PR DESCRIPTION
**Pull request by atodorov**
- Builds on top of #52. 
- Needs a functioning CI in order to execute and see that it works

### CODE REVIEW

**Review by pLabarta — APPROVED** [review]
LGTM, I'm ok with having it merged and failing till we redeploy devnet

**Review by nathanwhit — APPROVED** [review]
LGTM

**Review by nathanwhit — APPROVED** [review]
LGTM

**Comment by atodorov** [comment]
FTR the first ever & successfull job execution of this new workflow is
https://github.com/gluwa/creditcoin3/actions/runs/6902999873/job/18781125768, for commit https://github.com/gluwa/creditcoin3/commit/43f06ed182e72576cc4f7cbe8150b68c723ce7ef

Logs say:
```
 Runtime upgrade successfully scheduled
```

Meanwhile I was running some other tests against Devnet and saw the runtime being upgraded:
image

Note: version in top-left corner was `creditcoin3/4`  (for creditcoin3-3.4.1-devnet) before the upgrade.

**Pull request merged**
