### PR TITLE
CSUB-1099: Launch isolated creditcoin3-node processes before individual test groups

### PR DESCRIPTION
**Pull request by atodorov**
splitting https://github.com/gluwa/creditcoin3/pull/290 into multiple parts in order to find out which commit causes the failure seen when executing proxy=no in https://github.com/gluwa/creditcoin3/pull/290.

### CODE REVIEW

**Comment by atodorov** [comment]
FTR locally everything looks good: 

```
cli]$ yarn jest --silent --config src/test/integration-tests.config.ts --verbose --runInBand --forceExit src/test/integration-tests/
yarn run v1.22.21
$ /home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/.bin/jest --silent --config src/test/integration-tests.config.ts --verbose --runInBand --forceExit src/test/integration-tests/
 PASS  src/test/integration-tests/proxy.test.ts (459.234 s)
  Proxy functionality
    proxy list
      ✓ should display no proxies when none are configured (27432 ms)
      ✓ should display proxies which are configured (45469 ms)
    proxy add
      ✓ should execute without errors (49047 ms)
      ✓ should error when caller does not have funds to pay fees (31243 ms)
      ✓ should error when caller already has configured a proxy (44070 ms)
      ✓ should error when trying to configure a proxy used by another delegate (60141 ms)
    proxy remove
      ✓ should remove a configured proxy without errors (60135 ms)
      ✓ should error when caller does not have funds to pay fees (60123 ms)
      ✓ should error when no proxy defined (30720 ms)
      ✓ should error when removing a non-proxy address (44107 ms)

 PASS  src/test/integration-tests/send.test.ts (64.729 s)
  Send command
    ✓ should be able to send CTC (59017 ms)
    ○ skipped should error with account balance too low message
    ○ skipped should error with not-a-proxy message
    ○ skipped should error with no permission message

 PASS  src/test/integration-tests/balance.test.ts (64.938 s)
  balance
    ✓ should error when required option is not specified (15330 ms)
    ✓ should display balance (14864 ms)
    ✓ result should be JSON when --json specified (29405 ms)

 PASS  src/test/integration-tests/convertAddress.test.ts (6.562 s)
  Convert Address command
    ✓ should NOT convert an invalid EVM address (285 ms)
    ✓ should NOT convert an invalid Substrate address (293 ms)
    ✓ should convert a known Substrate address to a known EVM address (305 ms)
    ✓ should convert a known EVM address to a known Substrate address (292 ms)

 PASS  src/test/integration-tests/status.test.ts (6.564 s)
  status
    ✓ should error when required option is not specified (298 ms)
    ✓ should display validator & chain status when both are requested (471 ms)
    ✓ should display only validator status when --chain is not specified (490 ms)

 PASS  src/test/integration-tests/withdraw-unbonded.test.ts (1256.976 s)
  withdraw-unbonded
    when there are NO unlocked funds
      ✓ should error with no unlocked funds message (11451 ms)
    when funds have been unlocked
      ✓ should be able to withdraw (20146 ms)
      ○ skipped should error with account balance too low message
      ○ skipped should error with proxy.NotProxy message
    when partial unbond has been unlocked
      ✓ should be able to withdraw partially unlocked funds (20190 ms)

 PASS  src/test/integration-tests/validatorCycle.test.ts (1074.625 s)
  integration test: validator manual setup
    ✓ full validator cycle (1068868 ms)

 PASS  src/test/integration-tests/distribute-rewards.test.ts (324.062 s)
  distribute-rewards
    ✓ should distribute rewards (68500 ms)
    ✓ should fail when era not in history (51107 ms)
    ✓ should fail when address is not a validator (48874 ms)
    ○ skipped should error with account balance too low message
    ○ skipped should error with proxy.NotProxy message

 PASS  src/test/integration-tests/validate.test.ts (151.194 s)
  validate
    when NOT bonded
      ✓ should error with staking.NotController message (49512 ms)
    when ALREADY bonded
      ✓ should become a waiting validator (79975 ms)
      ○ skipped should error with account balance too low message
      ○ skipped should error with proxy.NotProxy message

 PASS  src/test/integration-tests/bond.test.ts (158.798 s)
  bond
    ✓ should bond specified amount + extra (84170 ms)
    ✓ should fail when already bonded (69076 ms)
    ○ skipped should error with account balance too low message
    ○ skipped should error with proxy.NotProxy message

 PASS  src/test/integration-tests/wizard.test.ts (101.827 s)
  wizard
    ✓ new validator should appear as waiting after running (79983 ms)
    ○ skipped should error with account balance too low message
    ○ skipped should error with proxy.NotProxy message

 PASS  src/test/integration-tests/evm.test.ts (189.352 s)
  EVM Commands
    EVM Fund
      ✓ should be able to fund an EVM account (28370 ms)
      ✓ should not be able to fund more than existing funds (16501 ms)
    EVM Withdraw
      ✓ should be able to withdraw CTC to a Substrate account via --url ws://127.0.0.1:9944 (49074 ms)
      ✓ should be able to withdraw CTC to a Substrate account via --url ws://127.0.0.1:9955 (45452 ms)
    EVM Balance
      ✓ should be able to show evm balance correctly when balance is zero (15020 ms)
      ✓ should be able to show balance correctly after funding (29409 ms)

 PASS  src/test/integration-tests/chill.test.ts (175.34 s)
  chill
    when NOT validating
      ✓ should error with validator not validating message (44797 ms)
    when ALREADY actively validating
      ✓ should cause validator to stop validating (110748 ms)
      ○ skipped should error with account balance too low message
      ○ skipped should error with proxy.NotProxy message

 PASS  src/test/integration-tests/unbond.test.ts (149.963 s)
  unbond
    when NOT bonded
      ✓ should error with validator not bonded message (44824 ms)
    when ALREADY bonded
      ✓ should be able to unbond (99611 ms)
      ○ skipped should error with account balance too low message
      ○ skipped should error with proxy.NotProxy message

 PASS  src/test/integration-tests/set-keys.test.ts (115.158 s)
  set-keys
    when NOT bonded
      ✓ should error when NO key options are specified (14042 ms)
      ✓ should error when BOTH key options are specified (16064 ms)
    when ALREADY bonded
      ✓ should set new keys (79485 ms)
      ○ skipped should error with account balance too low message
      ○ skipped should error with proxy.NotProxy message

 PASS  src/test/integration-tests/showAddress.test.ts (6.08 s)
  Show address command
    ✓ should return the correct address via --url ws://127.0.0.1:9944 (361 ms)
    ✓ should return the correct address via --url ws://127.0.0.1:9955 (365 ms)

Test Suites: 16 passed, 16 total
Tests:       19 skipped, 48 passed, 67 total
Snapshots:   0 total
Time:        4305.713 s, estimated 4411 s
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
Done in 4306.81s.
```

**Comment by zacharyfrederick** [comment]
in `runNode` have you ran a scenario where the function fails? I'm curious as to the error handling with it running in the background and using void over await

**Comment by atodorov** [comment]
> in `runNode` have you ran a scenario where the function fails? I'm curious as to the error handling with it running in the background and using void over await.

Using the following change:

```
$ git diff
diff --git a/cli/src/test/utils.ts b/cli/src/test/utils.ts
index 0e9e3a1..e3f4259 100644
--- a/cli/src/test/utils.ts
+++ b/cli/src/test/utils.ts
@@ -79,7 +79,7 @@ function runNode(name: string, extraArgs: string) {
 
     // warning: do NOT await, runs in background
     void execa(
-        '../target/release/creditcoin3-node',
+        '../target/release/creditcoin3-node2',
         `--chain dev --validator --pruning archive ${extraArgs}`.split(' '),
         {
             detached: true,
```

The results are:

```
$ yarn jest --config src/test/integration-tests.config.ts --verbose --runInBand --forceExit src/test/integration-tests/balance.test.ts 
yarn run v1.22.21
$ /home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/.bin/jest --config src/test/integration-tests.config.ts --verbose --runInBand --forceExit src/test/integration-tests/balance.test.ts
  console.log
    INFO: starting creditcoin3-node processes for Alice and Bob

      at startAliceAndBob (utils.ts:93:13)

  console.error
    2024-03-29 15:58:09          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure

      at apply (../../node_modules/@polkadot/util/cjs/logger.js:59:24)
      at Object.error (../../node_modules/@polkadot/util/cjs/logger.js:117:31)
      at WebSocket.__internal__onSocketClose (../../node_modules/@polkadot/rpc-provider/cjs/ws/index.js:355:15)
      at callListener (../../node_modules/ws/lib/event-target.js:290:14)
      at WebSocket.onClose (../../node_modules/ws/lib/event-target.js:220:9)
      at WebSocket.emitClose (../../node_modules/ws/lib/websocket.js:255:12)
      at emitErrorAndClose (../../node_modules/ws/lib/websocket.js:1034:13)
      at ClientRequest.<anonymous> (../../node_modules/ws/lib/websocket.js:880:5)

  console.error
    2024-03-29 15:58:11          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: Abnormal Closure

      at apply (../../node_modules/@polkadot/util/cjs/logger.js:59:24)
      at Object.error (../../node_modules/@polkadot/util/cjs/logger.js:117:31)
      at WebSocket.__internal__onSocketClose (../../node_modules/@polkadot/rpc-provider/cjs/ws/index.js:355:15)
      at callListener (../../node_modules/ws/lib/event-target.js:290:14)
      at WebSocket.onClose (../../node_modules/ws/lib/event-target.js:220:9)
      at WebSocket.emitClose (../../node_modules/ws/lib/websocket.js:255:12)
      at emitErrorAndClose (../../node_modules/ws/lib/websocket.js:1034:13)
      at ClientRequest.<anonymous> (../../node_modules/ws/lib/websocket.js:880:5)

  console.log
    INFO: killing all creditcoin3-node processes

      at killCreditcoinNodes (utils.ts:111:13)

 FAIL  src/test/integration-tests/balance.test.ts (12.165 s)
  ● balance › should error when required option is not specified

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       8 |     let sudoSigner: KeyringPair;
       9 |
    > 10 |     beforeAll(async () => {
         |     ^
      11 |         ({ api } = await newApi(ALICE_NODE_URL));
      12 |
      13 |         sudoSigner = initAliceKeyring();

      at integration-tests/balance.test.ts:10:5
      at Object.<anonymous> (integration-tests/balance.test.ts:4:1)

  ● balance › should display balance

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       8 |     let sudoSigner: KeyringPair;
       9 |
    > 10 |     beforeAll(async () => {
         |     ^
      11 |         ({ api } = await newApi(ALICE_NODE_URL));
      12 |
      13 |         sudoSigner = initAliceKeyring();

      at integration-tests/balance.test.ts:10:5
      at Object.<anonymous> (integration-tests/balance.test.ts:4:1)

  ● balance › result should be JSON when --json specified

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

       8 |     let sudoSigner: KeyringPair;
       9 |
    > 10 |     beforeAll(async () => {
         |     ^
      11 |         ({ api } = await newApi(ALICE_NODE_URL));
      12 |
      13 |         sudoSigner = initAliceKeyring();

      at integration-tests/balance.test.ts:10:5
      at Object.<anonymous> (integration-tests/balance.test.ts:4:1)


  ● Test suite failed to run

    spawn ../target/release/creditcoin3-node2 ENOENT



  ● Test suite failed to run

    spawn ../target/release/creditcoin3-node2 ENOENT



  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'disconnect')

      22 |
      23 |     afterAll(async () => {
    > 24 |         await api.disconnect();
         |                   ^
      25 |     });
      26 |
      27 |     it('should error when required option is not specified', () => {

      at Object.<anonymous> (integration-tests/balance.test.ts:24:19)

  ● Test suite failed to run

    Command failed with exit code 1: killall -9 creditcoin3-node
    creditcoin3-node: no process found

      111 |     console.log('INFO: killing all creditcoin3-node processes');
      112 |
    > 113 |     commandSync(`killall -9 creditcoin3-node`);
          |                ^
      114 | }
      115 |

      at makeError (../../node_modules/execa/lib/error.js:60:11)
      at Function.Object.<anonymous>.module.exports.sync (../../node_modules/execa/index.js:194:17)
      at Object.<anonymous>.module.exports.commandSync (../../node_modules/execa/index.js:235:15)
      at killCreditcoinNodes (utils.ts:113:16)
      at Object.<anonymous> (integrationTestSetupAfterEnv.ts:11:24)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        12.191 s, estimated 65 s
Ran all test suites matching /src\/test\/integration-tests\/balance.test.ts/i.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```


In the majority of cases I think we'll see the API not being able to connect before the `beforeAll` block inside the test times out. If lucky console logs or the node logs will tell us why it failed.


> 
> Edit: Ah nvm I didn't pay attention to how you are piping stdout and stderr. Nvm that should be enough for a user to catch it through the logs

**Review by DylanVerstraete — APPROVED** [review]
LGTM

**Review by zacharyfrederick — APPROVED** [review]

**Pull request merged**
